// Katalog kategori data — struktur & label mengikuti aplikasi referensi FT Teluk Betung.

export type ColumnType = "string" | "date" | "decimal" | "int" | "bigint";

export type DataColumn = { field: string; label: string; type: ColumnType };

export type DataCategory = {
  slug: string;
  table: string;
  label: string;
  group: string | null;
  hidden: boolean;
  readonly: boolean;
  csvUpload: boolean;
  noAdd?: boolean;
  columns: DataColumn[];
};

export const DATA_CATEGORIES: DataCategory[] = [
  {
    slug: "edc",
    table: "data_edc",
    label: "EDC",
    group: null,
    hidden: false,
    readonly: false,
    csvUpload: false,
    noAdd: true,
    columns: [
      { field: "posisi", label: "Posisi", type: "date" },
      { field: "nama_uker", label: "Nama Uker", type: "string" },
      { field: "tid", label: "TID", type: "string" },
      { field: "mid", label: "MID", type: "string" },
      { field: "nama_merchant", label: "Nama Merchant", type: "string" },
      { field: "uker_nama_implementor", label: "Uker Implementor", type: "string" },
      { field: "nama_user_pemrakarsa", label: "Nama User Pemrakarsa", type: "string" },
      { field: "alamat_merchant", label: "Alamat", type: "string" },
      { field: "sales_volume", label: "Sales Volume", type: "decimal" },
      { field: "saldo_posisi", label: "Saldo Posisi", type: "decimal" },
      { field: "tiering_sales_volume", label: "Tiering Sales Volume", type: "string" },
      { field: "status_edc", label: "Status EDC", type: "string" },
    ],
  },
  {
    slug: "qris",
    table: "data_qris",
    label: "QRIS",
    group: null,
    hidden: false,
    readonly: false,
    csvUpload: false,
    noAdd: true,
    columns: [
      { field: "periode", label: "Periode", type: "string" },
      { field: "posisi", label: "Posisi", type: "string" },
      { field: "region", label: "Region", type: "string" },
      { field: "rgdesc", label: "Rgdesc", type: "string" },
      { field: "mainbr", label: "Mainbr", type: "string" },
      { field: "mbdesc", label: "Mbdesc", type: "string" },
      { field: "branch", label: "Branch", type: "string" },
      { field: "x", label: "X", type: "string" },
      { field: "brdesc", label: "Brdesc", type: "string" },
      { field: "merchant_pan", label: "Merchant PAN", type: "string" },
      { field: "storeid", label: "Store ID", type: "string" },
      { field: "nama_merchant", label: "Nama Merchant", type: "string" },
      { field: "kriteria", label: "Kriteria", type: "string" },
      { field: "jenis_usaha", label: "Jenis Usaha", type: "string" },
      { field: "kode_mcc", label: "Kode MCC", type: "string" },
      { field: "mcc", label: "MCC", type: "string" },
      { field: "alamat", label: "Alamat", type: "string" },
      { field: "kode_pos", label: "Kode Pos", type: "string" },
      { field: "kota", label: "Kota", type: "string" },
      { field: "provinsi", label: "Provinsi", type: "string" },
      { field: "no_rek", label: "No Rek", type: "string" },
      { field: "cif", label: "CIF", type: "string" },
      { field: "pn", label: "PN", type: "string" },
      { field: "pn_pemrakasa", label: "PN Pemrakasa", type: "string" },
      { field: "jabatan", label: "Jabatan", type: "string" },
      { field: "tgl_balikan_pten", label: "Tgl Balikan PTEN", type: "string" },
      { field: "status", label: "Status", type: "string" },
      { field: "merchant_type", label: "Merchant Type", type: "string" },
      { field: "akumulasi_sv_onus", label: "Akumulasi SV Onus", type: "decimal" },
      { field: "akumulasi_sv_offus", label: "Akumulasi SV Offus", type: "decimal" },
      { field: "akumulasi_sv_linkaja", label: "Akumulasi SV LinkAja", type: "decimal" },
      { field: "akumulasi_sv_total", label: "Akumulasi SV Total", type: "decimal" },
      { field: "posisi_sv_total", label: "Posisi SV Total", type: "decimal" },
      { field: "akumulasi_trx_onus", label: "Akumulasi TRX Onus", type: "decimal" },
      { field: "akumulasi_trx_offus", label: "Akumulasi TRX Offus", type: "decimal" },
      { field: "akumulasi_trx_linkaja", label: "Akumulasi TRX LinkAja", type: "decimal" },
      { field: "akumulasi_trx_total", label: "Akumulasi TRX Total", type: "decimal" },
      { field: "posisi_trx_total", label: "Posisi TRX Total", type: "decimal" },
      { field: "saldo_posisi", label: "Saldo Posisi", type: "decimal" },
      { field: "ratas_saldo", label: "Ratas Saldo", type: "decimal" },
      { field: "flagging_bri_merchant", label: "Flagging BRI Merchant", type: "string" },
      { field: "status_qris", label: "Status QRIS", type: "string" },
    ],
  },
  {
    slug: "di319_data1",
    table: "data_di319_data1",
    label: "DATA1",
    group: "DI319",
    hidden: false,
    readonly: false,
    csvUpload: false,
    noAdd: true,
    columns: [
      { field: "periode", label: "Periode", type: "string" },
      { field: "uker_code", label: "Uker Code", type: "string" },
      { field: "curr_code", label: "Curr Code", type: "string" },
      { field: "curr_desc", label: "Curr Desc", type: "string" },
      { field: "account_number", label: "Account Number", type: "string" },
      { field: "ciff_no", label: "CIFF No", type: "string" },
      { field: "short_name", label: "Short Name", type: "string" },
      { field: "open_dt", label: "Open Dt", type: "date" },
      { field: "balance", label: "Balance", type: "decimal" },
      { field: "in_balance", label: "In Balance", type: "decimal" },
      { field: "accrued_int", label: "Accrued Int", type: "decimal" },
      { field: "average_balance", label: "Average Balance", type: "decimal" },
      { field: "prod_code", label: "Prod Code", type: "string" },
      { field: "pn_pengelola_singlepn", label: "PN Pengelola SinglePN", type: "string" },
      { field: "pn_customer_service", label: "PN Customer Service", type: "string" },
      { field: "pn_rm_dana_mantri", label: "PN RM Dana/Mantri", type: "string" },
      { field: "pn_rm_pinjaman", label: "PN RM Pinjaman", type: "string" },
      { field: "pn_rm_merchant", label: "PN RM Merchant", type: "string" },
      { field: "pn_relationship_officer_rm_kredit_menengah", label: "PN Relationship Officer/RM Kredit Menengah", type: "string" },
      { field: "pn_sales_person", label: "PN Sales Person", type: "string" },
      { field: "pn_pab", label: "PN PAB", type: "string" },
      { field: "pn_rm_referral", label: "PN RM Referral", type: "string" },
      { field: "jumlah_pn_pemasar", label: "Jumlah PN Pemasar", type: "int" },
      { field: "balance_dalam_idr", label: "Balance Dalam IDR", type: "decimal" },
    ],
  },
  {
    slug: "di319_data2",
    table: "data_di319_data2",
    label: "DATA2",
    group: "DI319",
    hidden: false,
    readonly: false,
    csvUpload: false,
    noAdd: true,
    columns: [
      { field: "periode", label: "Periode", type: "string" },
      { field: "uker_code", label: "Uker Code", type: "string" },
      { field: "curr_code", label: "Curr Code", type: "string" },
      { field: "curr_desc", label: "Curr Desc", type: "string" },
      { field: "account_number", label: "Account Number", type: "string" },
      { field: "ciff_no", label: "CIFF No", type: "string" },
      { field: "short_name", label: "Short Name", type: "string" },
      { field: "open_dt", label: "Open Dt", type: "date" },
      { field: "balance", label: "Balance", type: "decimal" },
      { field: "in_balance", label: "In Balance", type: "decimal" },
      { field: "accrued_int", label: "Accrued Int", type: "decimal" },
      { field: "average_balance", label: "Average Balance", type: "decimal" },
      { field: "prod_code", label: "Prod Code", type: "string" },
      { field: "pn_pengelola_singlepn", label: "PN Pengelola SinglePN", type: "string" },
      { field: "pn_customer_service", label: "PN Customer Service", type: "string" },
      { field: "pn_rm_dana_mantri", label: "PN RM Dana/Mantri", type: "string" },
      { field: "pn_rm_pinjaman", label: "PN RM Pinjaman", type: "string" },
      { field: "pn_rm_merchant", label: "PN RM Merchant", type: "string" },
      { field: "pn_relationship_officer_rm_kredit_menengah", label: "PN Relationship Officer/RM Kredit Menengah", type: "string" },
      { field: "pn_sales_person", label: "PN Sales Person", type: "string" },
      { field: "pn_pab", label: "PN PAB", type: "string" },
      { field: "pn_rm_referral", label: "PN RM Referral", type: "string" },
      { field: "jumlah_pn_pemasar", label: "Jumlah PN Pemasar", type: "int" },
      { field: "balance_dalam_idr", label: "Balance Dalam IDR", type: "decimal" },
    ],
  },
  {
    slug: "di319_data3",
    table: "data_di319_data3",
    label: "DATA3",
    group: "DI319",
    hidden: false,
    readonly: false,
    csvUpload: false,
    noAdd: true,
    columns: [
      { field: "periode", label: "Periode", type: "string" },
      { field: "uker_code", label: "Uker Code", type: "string" },
      { field: "curr_code", label: "Curr Code", type: "string" },
      { field: "curr_desc", label: "Curr Desc", type: "string" },
      { field: "account_number", label: "Account Number", type: "string" },
      { field: "ciff_no", label: "CIFF No", type: "string" },
      { field: "short_name", label: "Short Name", type: "string" },
      { field: "open_dt", label: "Open Dt", type: "date" },
      { field: "balance", label: "Balance", type: "decimal" },
      { field: "in_balance", label: "In Balance", type: "decimal" },
      { field: "accrued_int", label: "Accrued Int", type: "decimal" },
      { field: "average_balance", label: "Average Balance", type: "decimal" },
      { field: "prod_code", label: "Prod Code", type: "string" },
      { field: "pn_pengelola_singlepn", label: "PN Pengelola SinglePN", type: "string" },
      { field: "pn_customer_service", label: "PN Customer Service", type: "string" },
      { field: "pn_rm_dana_mantri", label: "PN RM Dana/Mantri", type: "string" },
      { field: "pn_rm_pinjaman", label: "PN RM Pinjaman", type: "string" },
      { field: "pn_rm_merchant", label: "PN RM Merchant", type: "string" },
      { field: "pn_relationship_officer_rm_kredit_menengah", label: "PN Relationship Officer/RM Kredit Menengah", type: "string" },
      { field: "pn_sales_person", label: "PN Sales Person", type: "string" },
      { field: "pn_pab", label: "PN PAB", type: "string" },
      { field: "pn_rm_referral", label: "PN RM Referral", type: "string" },
      { field: "jumlah_pn_pemasar", label: "Jumlah PN Pemasar", type: "int" },
      { field: "balance_dalam_idr", label: "Balance Dalam IDR", type: "decimal" },
    ],
  },
  {
    slug: "di321_data1",
    table: "data_di321_data1",
    label: "DATA1",
    group: "DI321",
    hidden: false,
    readonly: false,
    csvUpload: false,
    noAdd: true,
    columns: [
      { field: "periode", label: "Periode", type: "string" },
      { field: "kanca", label: "Kanca", type: "string" },
      { field: "curr", label: "Curr", type: "string" },
      { field: "cifno", label: "CIF No", type: "string" },
      { field: "account_number", label: "Account Number", type: "string" },
      { field: "short_name", label: "Short Name", type: "string" },
      { field: "balance", label: "Balance", type: "decimal" },
      { field: "pn_rm_dana", label: "PN RM Dana", type: "string" },
      { field: "pn_rm_pinjaman", label: "PN RM Pinjaman", type: "string" },
      { field: "pn_rm_merchant", label: "PN RM Merchant", type: "string" },
      { field: "pn_relationship_officer", label: "PN Relationship Officer", type: "string" },
    ],
  },
  {
    slug: "di321_data2",
    table: "data_di321_data2",
    label: "DATA2",
    group: "DI321",
    hidden: false,
    readonly: false,
    csvUpload: false,
    noAdd: true,
    columns: [
      { field: "periode", label: "Periode", type: "string" },
      { field: "kanca", label: "Kanca", type: "string" },
      { field: "curr", label: "Curr", type: "string" },
      { field: "cifno", label: "CIF No", type: "string" },
      { field: "account_number", label: "Account Number", type: "string" },
      { field: "short_name", label: "Short Name", type: "string" },
      { field: "balance", label: "Balance", type: "decimal" },
      { field: "pn_rm_dana", label: "PN RM Dana", type: "string" },
      { field: "pn_rm_pinjaman", label: "PN RM Pinjaman", type: "string" },
      { field: "pn_rm_merchant", label: "PN RM Merchant", type: "string" },
      { field: "pn_relationship_officer", label: "PN Relationship Officer", type: "string" },
    ],
  },
  {
    slug: "di321_data3",
    table: "data_di321_data3",
    label: "DATA3",
    group: "DI321",
    hidden: false,
    readonly: false,
    csvUpload: false,
    noAdd: true,
    columns: [
      { field: "periode", label: "Periode", type: "string" },
      { field: "kanca", label: "Kanca", type: "string" },
      { field: "curr", label: "Curr", type: "string" },
      { field: "cifno", label: "CIF No", type: "string" },
      { field: "account_number", label: "Account Number", type: "string" },
      { field: "short_name", label: "Short Name", type: "string" },
      { field: "balance", label: "Balance", type: "decimal" },
      { field: "pn_rm_dana", label: "PN RM Dana", type: "string" },
      { field: "pn_rm_pinjaman", label: "PN RM Pinjaman", type: "string" },
      { field: "pn_rm_merchant", label: "PN RM Merchant", type: "string" },
      { field: "pn_relationship_officer", label: "PN Relationship Officer", type: "string" },
    ],
  },
  {
    slug: "depo_data1",
    table: "data_depo_data1",
    label: "DATA1",
    group: "DEPO",
    hidden: false,
    readonly: false,
    csvUpload: false,
    noAdd: true,
    columns: [
      { field: "periode", label: "Periode", type: "string" },
      { field: "kode_uker", label: "Kode Uker", type: "string" },
      { field: "cur_code", label: "Cur Code", type: "string" },
      { field: "cur_desc", label: "Cur Desc", type: "string" },
      { field: "type", label: "Type", type: "string" },
      { field: "acctno", label: "Acctno", type: "string" },
      { field: "fdr_srl_no", label: "FDR Srl No", type: "string" },
      { field: "principal_amount", label: "Principal Amount", type: "decimal" },
      { field: "short_name", label: "Short Name", type: "string" },
      { field: "withdrawable_int", label: "Withdrawable Int", type: "decimal" },
      { field: "issue_dt", label: "Issue Dt", type: "string" },
      { field: "mat_dt", label: "Mat Dt", type: "string" },
      { field: "int_rate", label: "Int Rate", type: "decimal" },
      { field: "int_tenor_disp", label: "Int Tenor Disp", type: "string" },
      { field: "renew", label: "Renew", type: "string" },
      { field: "remark", label: "Remark", type: "string" },
      { field: "pn_customer_service", label: "PN Customer Service", type: "string" },
      { field: "pn_rm_dana", label: "PN RM Dana", type: "string" },
      { field: "pn_rm_pinjaman", label: "PN RM Pinjaman", type: "string" },
      { field: "pn_rm_merchant", label: "PN RM Merchant", type: "string" },
      { field: "pn_relationship_officer", label: "PN Relationship Officer", type: "string" },
      { field: "pn_sales_person", label: "PN Sales Person", type: "string" },
      { field: "pn_pab", label: "PN PAB", type: "string" },
      { field: "pn_rm_referral", label: "PN RM Referral", type: "string" },
      { field: "jumlah_pn", label: "Jumlah PN", type: "decimal" },
      { field: "cbal_base", label: "CBAL Base", type: "decimal" },
    ],
  },
  {
    slug: "depo_data2",
    table: "data_depo_data2",
    label: "DATA2",
    group: "DEPO",
    hidden: false,
    readonly: false,
    csvUpload: false,
    noAdd: true,
    columns: [
      { field: "periode", label: "Periode", type: "string" },
      { field: "kode_uker", label: "Kode Uker", type: "string" },
      { field: "cur_code", label: "Cur Code", type: "string" },
      { field: "cur_desc", label: "Cur Desc", type: "string" },
      { field: "type", label: "Type", type: "string" },
      { field: "acctno", label: "Acctno", type: "string" },
      { field: "fdr_srl_no", label: "FDR Srl No", type: "string" },
      { field: "principal_amount", label: "Principal Amount", type: "decimal" },
      { field: "short_name", label: "Short Name", type: "string" },
      { field: "withdrawable_int", label: "Withdrawable Int", type: "decimal" },
      { field: "issue_dt", label: "Issue Dt", type: "string" },
      { field: "mat_dt", label: "Mat Dt", type: "string" },
      { field: "int_rate", label: "Int Rate", type: "decimal" },
      { field: "int_tenor_disp", label: "Int Tenor Disp", type: "string" },
      { field: "renew", label: "Renew", type: "string" },
      { field: "remark", label: "Remark", type: "string" },
      { field: "pn_customer_service", label: "PN Customer Service", type: "string" },
      { field: "pn_rm_dana", label: "PN RM Dana", type: "string" },
      { field: "pn_rm_pinjaman", label: "PN RM Pinjaman", type: "string" },
      { field: "pn_rm_merchant", label: "PN RM Merchant", type: "string" },
      { field: "pn_relationship_officer", label: "PN Relationship Officer", type: "string" },
      { field: "pn_sales_person", label: "PN Sales Person", type: "string" },
      { field: "pn_pab", label: "PN PAB", type: "string" },
      { field: "pn_rm_referral", label: "PN RM Referral", type: "string" },
      { field: "jumlah_pn", label: "Jumlah PN", type: "decimal" },
      { field: "cbal_base", label: "CBAL Base", type: "decimal" },
    ],
  },
  {
    slug: "depo_data3",
    table: "data_depo_data3",
    label: "DATA3",
    group: "DEPO",
    hidden: false,
    readonly: false,
    csvUpload: false,
    noAdd: true,
    columns: [
      { field: "periode", label: "Periode", type: "string" },
      { field: "kode_uker", label: "Kode Uker", type: "string" },
      { field: "cur_code", label: "Cur Code", type: "string" },
      { field: "cur_desc", label: "Cur Desc", type: "string" },
      { field: "type", label: "Type", type: "string" },
      { field: "acctno", label: "Acctno", type: "string" },
      { field: "fdr_srl_no", label: "FDR Srl No", type: "string" },
      { field: "principal_amount", label: "Principal Amount", type: "decimal" },
      { field: "short_name", label: "Short Name", type: "string" },
      { field: "withdrawable_int", label: "Withdrawable Int", type: "decimal" },
      { field: "issue_dt", label: "Issue Dt", type: "string" },
      { field: "mat_dt", label: "Mat Dt", type: "string" },
      { field: "int_rate", label: "Int Rate", type: "decimal" },
      { field: "int_tenor_disp", label: "Int Tenor Disp", type: "string" },
      { field: "renew", label: "Renew", type: "string" },
      { field: "remark", label: "Remark", type: "string" },
      { field: "pn_customer_service", label: "PN Customer Service", type: "string" },
      { field: "pn_rm_dana", label: "PN RM Dana", type: "string" },
      { field: "pn_rm_pinjaman", label: "PN RM Pinjaman", type: "string" },
      { field: "pn_rm_merchant", label: "PN RM Merchant", type: "string" },
      { field: "pn_relationship_officer", label: "PN Relationship Officer", type: "string" },
      { field: "pn_sales_person", label: "PN Sales Person", type: "string" },
      { field: "pn_pab", label: "PN PAB", type: "string" },
      { field: "pn_rm_referral", label: "PN RM Referral", type: "string" },
      { field: "jumlah_pn", label: "Jumlah PN", type: "decimal" },
      { field: "cbal_base", label: "CBAL Base", type: "decimal" },
    ],
  },
  {
    slug: "pic_jalan",
    table: "data_pic_jalan",
    label: "PIC JALAN",
    group: null,
    hidden: false,
    readonly: false,
    csvUpload: false,
    columns: [
      { field: "no_urut", label: "No Urut", type: "int" },
      { field: "unit_kerja", label: "Unit Kerja", type: "string" },
      { field: "nama_rmft", label: "Nama RMFT", type: "string" },
      { field: "nama_jalan", label: "Nama Jalan", type: "string" },
      { field: "nama_toko", label: "Nama Toko", type: "string" },
      { field: "usaha", label: "Usaha", type: "string" },
      { field: "rek_bri", label: "Rek BRI", type: "string" },
      { field: "edc_bri", label: "EDC BRI", type: "string" },
      { field: "qris_bri", label: "QRIS BRI", type: "string" },
      { field: "rek_lain", label: "Rek Lain", type: "string" },
      { field: "edc_lain", label: "EDC Lain", type: "string" },
      { field: "qris_lain", label: "QRIS Lain", type: "string" },
      { field: "telpon", label: "Telpon", type: "string" },
      { field: "owner", label: "Owner", type: "string" },
      { field: "keterangan", label: "Keterangan", type: "string" },
      { field: "follow_up_terakhir", label: "Follow Up Terakhir", type: "date" },
    ],
  },
  {
    slug: "produktivitas_rmft",
    table: "data_produktivitas_rmft",
    label: "PRODUKTIVITAS RMFT",
    group: null,
    hidden: false,
    readonly: false,
    csvUpload: false,
    columns: [
      { field: "rm", label: "RM", type: "string" },
      { field: "dpk", label: "DPK", type: "string" },
      { field: "tgl1", label: "tgl 1", type: "decimal" },
      { field: "tgl2", label: "tgl 2", type: "decimal" },
      { field: "tgl3", label: "tgl 3", type: "decimal" },
    ],
  },
  {
    slug: "pivot_multi",
    table: "data_pivot_multi",
    label: "PIVOT MULTI",
    group: null,
    hidden: false,
    readonly: false,
    csvUpload: true,
    noAdd: true,
    columns: [
      { field: "seq", label: "Seq", type: "int" },
      { field: "no_rek", label: "No Rek", type: "string" },
      { field: "nama", label: "Nama", type: "string" },
      { field: "valuta", label: "Valuta", type: "string" },
      { field: "jenis_rekening", label: "Jenis Rekening", type: "string" },
      { field: "tanggal_transaksi", label: "Tanggal Transaksi", type: "date" },
      { field: "jam_transaksi", label: "Jam Transaksi", type: "string" },
      { field: "kode_transaksi", label: "Kode Transaksi", type: "string" },
      { field: "desk_transaksi", label: "Desk Transaksi", type: "string" },
      { field: "saldo_awal_mutasi", label: "Saldo Awal Mutasi", type: "decimal" },
      { field: "mutasi_debet", label: "Mutasi Debet", type: "decimal" },
      { field: "mutasi_kredit", label: "Mutasi Kredit", type: "decimal" },
      { field: "saldo_akhir_mutasi", label: "Saldo Akhir Mutasi", type: "decimal" },
      { field: "truser", label: "TR User", type: "string" },
      { field: "glsign", label: "GL Sign", type: "string" },
      { field: "auxtrc", label: "Auxtrc", type: "string" },
      { field: "uker_tran", label: "Uker Tran", type: "string" },
      { field: "uker_desc_tran", label: "Uker Desc Tran", type: "string" },
    ],
  },
  {
    slug: "mtd_tab",
    table: "data_mtd_tab",
    label: "MTD TAB",
    group: "MTD YTD",
    hidden: false,
    readonly: true,
    csvUpload: false,
    columns: [
      { field: "periode", label: "Periode", type: "string" },
      { field: "kode_kanwil", label: "Kode Kanwil", type: "string" },
      { field: "kanwil", label: "Kanwil", type: "string" },
      { field: "kode_kanca", label: "Kode Kanca", type: "string" },
      { field: "kanca", label: "Kanca", type: "string" },
      { field: "kode_uker", label: "Kode Uker", type: "string" },
      { field: "uker", label: "Uker", type: "string" },
      { field: "curr", label: "Curr", type: "string" },
      { field: "currdesc", label: "Curr Desc", type: "string" },
      { field: "cifno", label: "CIF No", type: "string" },
      { field: "account_number", label: "Account Number", type: "bigint" },
      { field: "product_code", label: "Product Code", type: "string" },
      { field: "status", label: "Status", type: "int" },
      { field: "short_name", label: "Short Name", type: "string" },
      { field: "open_date", label: "Open Date", type: "date" },
      { field: "balance", label: "Balance", type: "decimal" },
      { field: "avail_balance", label: "Avail Balance", type: "decimal" },
      { field: "limit_amount", label: "Limit Amount", type: "decimal" },
      { field: "cr_int", label: "Cr Int", type: "decimal" },
      { field: "dr_int", label: "Dr Int", type: "decimal" },
      { field: "commitment", label: "Commitment", type: "decimal" },
      { field: "avrg_balance", label: "Avrg Balance", type: "decimal" },
      { field: "pn_pengelola_single_pn", label: "PN Pengelola Single PN", type: "string" },
      { field: "pn_customer_service", label: "PN Customer Service", type: "string" },
      { field: "pn_rm_dana", label: "PN RM Dana", type: "string" },
      { field: "pn_rm_pinjaman", label: "PN RM Pinjaman", type: "string" },
      { field: "pn_rm_merchant", label: "PN RM Merchant", type: "string" },
      { field: "pn_relationship_officer", label: "PN Relationship Officer", type: "string" },
      { field: "pn_sales_person", label: "PN Sales Person", type: "string" },
      { field: "pn_pab", label: "PN PAB", type: "string" },
      { field: "pn_rm_referral", label: "PN RM Referral", type: "string" },
    ],
  },
  {
    slug: "ytd_tab",
    table: "data_ytd_tab",
    label: "YTD TAB",
    group: "MTD YTD",
    hidden: false,
    readonly: true,
    csvUpload: false,
    columns: [
      { field: "periode", label: "Periode", type: "string" },
      { field: "kode_kanwil", label: "Kode Kanwil", type: "string" },
      { field: "kanwil", label: "Kanwil", type: "string" },
      { field: "kode_kanca", label: "Kode Kanca", type: "string" },
      { field: "kanca", label: "Kanca", type: "string" },
      { field: "kode_uker", label: "Kode Uker", type: "string" },
      { field: "uker", label: "Uker", type: "string" },
      { field: "curr", label: "Curr", type: "string" },
      { field: "currdesc", label: "Curr Desc", type: "string" },
      { field: "cifno", label: "CIF No", type: "string" },
      { field: "account_number", label: "Account Number", type: "bigint" },
      { field: "product_code", label: "Product Code", type: "string" },
      { field: "status", label: "Status", type: "int" },
      { field: "short_name", label: "Short Name", type: "string" },
      { field: "open_date", label: "Open Date", type: "date" },
      { field: "balance", label: "Balance", type: "decimal" },
      { field: "avail_balance", label: "Avail Balance", type: "decimal" },
      { field: "limit_amount", label: "Limit Amount", type: "decimal" },
      { field: "cr_int", label: "Cr Int", type: "decimal" },
      { field: "dr_int", label: "Dr Int", type: "decimal" },
      { field: "commitment", label: "Commitment", type: "decimal" },
      { field: "avrg_balance", label: "Avrg Balance", type: "decimal" },
      { field: "pn_pengelola_single_pn", label: "PN Pengelola Single PN", type: "string" },
      { field: "pn_customer_service", label: "PN Customer Service", type: "string" },
      { field: "pn_rm_dana", label: "PN RM Dana", type: "string" },
      { field: "pn_rm_pinjaman", label: "PN RM Pinjaman", type: "string" },
      { field: "pn_rm_merchant", label: "PN RM Merchant", type: "string" },
      { field: "pn_relationship_officer", label: "PN Relationship Officer", type: "string" },
      { field: "pn_sales_person", label: "PN Sales Person", type: "string" },
      { field: "pn_pab", label: "PN PAB", type: "string" },
      { field: "pn_rm_referral", label: "PN RM Referral", type: "string" },
    ],
  },
  {
    slug: "mtd_giro",
    table: "data_mtd_giro",
    label: "MTD GIRO",
    group: "MTD YTD",
    hidden: false,
    readonly: true,
    csvUpload: false,
    columns: [
      { field: "periode", label: "Periode", type: "string" },
      { field: "kode_kanwil", label: "Kode Kanwil", type: "string" },
      { field: "kanwil", label: "Kanwil", type: "string" },
      { field: "kode_kanca", label: "Kode Kanca", type: "string" },
      { field: "kanca", label: "Kanca", type: "string" },
      { field: "kode_uker", label: "Kode Uker", type: "string" },
      { field: "uker", label: "Uker", type: "string" },
      { field: "curr", label: "Curr", type: "string" },
      { field: "currdesc", label: "Curr Desc", type: "string" },
      { field: "cifno", label: "CIF No", type: "string" },
      { field: "account_number", label: "Account Number", type: "bigint" },
      { field: "product_code", label: "Product Code", type: "string" },
      { field: "status", label: "Status", type: "int" },
      { field: "short_name", label: "Short Name", type: "string" },
      { field: "open_date", label: "Open Date", type: "date" },
      { field: "balance", label: "Balance", type: "decimal" },
      { field: "avail_balance", label: "Avail Balance", type: "decimal" },
      { field: "limit_amount", label: "Limit Amount", type: "decimal" },
      { field: "cr_int", label: "Cr Int", type: "decimal" },
      { field: "dr_int", label: "Dr Int", type: "decimal" },
      { field: "commitment", label: "Commitment", type: "decimal" },
      { field: "avrg_balance", label: "Avrg Balance", type: "decimal" },
      { field: "pn_pengelola_single_pn", label: "PN Pengelola Single PN", type: "string" },
      { field: "pn_customer_service", label: "PN Customer Service", type: "string" },
      { field: "pn_rm_dana", label: "PN RM Dana", type: "string" },
      { field: "pn_rm_pinjaman", label: "PN RM Pinjaman", type: "string" },
      { field: "pn_rm_merchant", label: "PN RM Merchant", type: "string" },
      { field: "pn_relationship_officer", label: "PN Relationship Officer", type: "string" },
      { field: "pn_sales_person", label: "PN Sales Person", type: "string" },
      { field: "pn_pab", label: "PN PAB", type: "string" },
      { field: "pn_rm_referral", label: "PN RM Referral", type: "string" },
    ],
  },
  {
    slug: "ytd_giro",
    table: "data_ytd_giro",
    label: "YTD GIRO",
    group: "MTD YTD",
    hidden: false,
    readonly: true,
    csvUpload: false,
    columns: [
      { field: "periode", label: "Periode", type: "string" },
      { field: "kode_kanwil", label: "Kode Kanwil", type: "string" },
      { field: "kanwil", label: "Kanwil", type: "string" },
      { field: "kode_kanca", label: "Kode Kanca", type: "string" },
      { field: "kanca", label: "Kanca", type: "string" },
      { field: "kode_uker", label: "Kode Uker", type: "string" },
      { field: "uker", label: "Uker", type: "string" },
      { field: "curr", label: "Curr", type: "string" },
      { field: "currdesc", label: "Curr Desc", type: "string" },
      { field: "cifno", label: "CIF No", type: "string" },
      { field: "account_number", label: "Account Number", type: "bigint" },
      { field: "product_code", label: "Product Code", type: "string" },
      { field: "status", label: "Status", type: "int" },
      { field: "short_name", label: "Short Name", type: "string" },
      { field: "open_date", label: "Open Date", type: "date" },
      { field: "balance", label: "Balance", type: "decimal" },
      { field: "avail_balance", label: "Avail Balance", type: "decimal" },
      { field: "limit_amount", label: "Limit Amount", type: "decimal" },
      { field: "cr_int", label: "Cr Int", type: "decimal" },
      { field: "dr_int", label: "Dr Int", type: "decimal" },
      { field: "commitment", label: "Commitment", type: "decimal" },
      { field: "avrg_balance", label: "Avrg Balance", type: "decimal" },
      { field: "pn_pengelola_single_pn", label: "PN Pengelola Single PN", type: "string" },
      { field: "pn_customer_service", label: "PN Customer Service", type: "string" },
      { field: "pn_rm_dana", label: "PN RM Dana", type: "string" },
      { field: "pn_rm_pinjaman", label: "PN RM Pinjaman", type: "string" },
      { field: "pn_rm_merchant", label: "PN RM Merchant", type: "string" },
      { field: "pn_relationship_officer", label: "PN Relationship Officer", type: "string" },
      { field: "pn_sales_person", label: "PN Sales Person", type: "string" },
      { field: "pn_pab", label: "PN PAB", type: "string" },
      { field: "pn_rm_referral", label: "PN RM Referral", type: "string" },
    ],
  },
  {
    slug: "mtd_tab_penurunan",
    table: "data_mtd_tab_penurunan",
    label: "Penurunan",
    group: null,
    hidden: true,
    readonly: true,
    csvUpload: false,
    columns: [
      { field: "norek", label: "Norek", type: "string" },
      { field: "nama_nasabah", label: "Nama Nasabah", type: "string" },
      { field: "tgl1", label: "tgl 1", type: "decimal" },
      { field: "tgl2", label: "tgl 2", type: "decimal" },
      { field: "rm_pengelola", label: "RM Pengelola", type: "string" },
    ],
  },
  {
    slug: "mtd_tab_kenaikan",
    table: "data_mtd_tab_kenaikan",
    label: "Kenaikan",
    group: null,
    hidden: true,
    readonly: true,
    csvUpload: false,
    columns: [
      { field: "norek", label: "Norek", type: "string" },
      { field: "nama_nasabah", label: "Nama Nasabah", type: "string" },
      { field: "tgl1", label: "tgl 1", type: "decimal" },
      { field: "tgl2", label: "tgl 2", type: "decimal" },
      { field: "rm_pengelola", label: "RM Pengelola", type: "string" },
    ],
  },
  {
    slug: "ytd_tab_penurunan",
    table: "data_ytd_tab_penurunan",
    label: "Penurunan",
    group: null,
    hidden: true,
    readonly: true,
    csvUpload: false,
    columns: [
      { field: "norek", label: "Norek", type: "string" },
      { field: "nama_nasabah", label: "Nama Nasabah", type: "string" },
      { field: "tgl1", label: "tgl 1", type: "decimal" },
      { field: "tgl2", label: "tgl 2", type: "decimal" },
      { field: "rm_pengelola", label: "RM Pengelola", type: "string" },
    ],
  },
  {
    slug: "ytd_tab_kenaikan",
    table: "data_ytd_tab_kenaikan",
    label: "Kenaikan",
    group: null,
    hidden: true,
    readonly: true,
    csvUpload: false,
    columns: [
      { field: "norek", label: "Norek", type: "string" },
      { field: "nama_nasabah", label: "Nama Nasabah", type: "string" },
      { field: "tgl1", label: "tgl 1", type: "decimal" },
      { field: "tgl2", label: "tgl 2", type: "decimal" },
      { field: "rm_pengelola", label: "RM Pengelola", type: "string" },
    ],
  },
  {
    slug: "mtd_giro_penurunan",
    table: "data_mtd_giro_penurunan",
    label: "Penurunan",
    group: null,
    hidden: true,
    readonly: true,
    csvUpload: false,
    columns: [
      { field: "norek", label: "Norek", type: "string" },
      { field: "nama_nasabah", label: "Nama Nasabah", type: "string" },
      { field: "tgl1", label: "tgl 1", type: "decimal" },
      { field: "tgl2", label: "tgl 2", type: "decimal" },
      { field: "rm_pengelola", label: "RM Pengelola", type: "string" },
    ],
  },
  {
    slug: "mtd_giro_kenaikan",
    table: "data_mtd_giro_kenaikan",
    label: "Kenaikan",
    group: null,
    hidden: true,
    readonly: true,
    csvUpload: false,
    columns: [
      { field: "norek", label: "Norek", type: "string" },
      { field: "nama_nasabah", label: "Nama Nasabah", type: "string" },
      { field: "tgl1", label: "tgl 1", type: "decimal" },
      { field: "tgl2", label: "tgl 2", type: "decimal" },
      { field: "rm_pengelola", label: "RM Pengelola", type: "string" },
    ],
  },
  {
    slug: "ytd_giro_penurunan",
    table: "data_ytd_giro_penurunan",
    label: "Penurunan",
    group: null,
    hidden: true,
    readonly: true,
    csvUpload: false,
    columns: [
      { field: "norek", label: "Norek", type: "string" },
      { field: "nama_nasabah", label: "Nama Nasabah", type: "string" },
      { field: "tgl1", label: "tgl 1", type: "decimal" },
      { field: "tgl2", label: "tgl 2", type: "decimal" },
      { field: "rm_pengelola", label: "RM Pengelola", type: "string" },
    ],
  },
  {
    slug: "ytd_giro_kenaikan",
    table: "data_ytd_giro_kenaikan",
    label: "Kenaikan",
    group: null,
    hidden: true,
    readonly: true,
    csvUpload: false,
    columns: [
      { field: "norek", label: "Norek", type: "string" },
      { field: "nama_nasabah", label: "Nama Nasabah", type: "string" },
      { field: "tgl1", label: "tgl 1", type: "decimal" },
      { field: "tgl2", label: "tgl 2", type: "decimal" },
      { field: "rm_pengelola", label: "RM Pengelola", type: "string" },
    ],
  },
];

export const CATEGORY_BY_SLUG = new Map(DATA_CATEGORIES.map((c) => [c.slug, c]));

/** Kategori yang tampil di sidebar (tidak hidden). */
export const VISIBLE_CATEGORIES = DATA_CATEGORIES.filter((c) => !c.hidden);

/** Kolom teks pertama dipakai sebagai kolom pencarian default. */
export function searchColumnOf(c: DataCategory) {
  return c.columns.find((x) => x.type === "string")?.field;
}
