-- ============================================================================
-- BO Teluk Betung — Skema database PostgreSQL (self-hosted / cPanel HawkHost)
-- Database : teknolo8_boteluk_uji
-- User     : teknolo8_botelukuji
--
-- Cara pakai (Terminal cPanel atau phpPgAdmin):
--   psql -U teknolo8_botelukuji -d teknolo8_boteluk_uji -f database.sql
--
-- Login awal:  username = admin   password = admin123
-- SEGERA ganti password admin setelah login pertama.
-- ============================================================================

-- UUID generator mandiri (tidak bergantung pada pgcrypto maupun PostgreSQL 13+).
-- Dipakai sebagai DEFAULT kolom id agar import selalu berhasil di shared hosting.
CREATE OR REPLACE FUNCTION public.app_uuid() RETURNS uuid
LANGUAGE sql VOLATILE AS $$
  SELECT (
    substr(md5(random()::text || clock_timestamp()::text), 1, 8) || '-' ||
    substr(md5(random()::text || clock_timestamp()::text), 1, 4) || '-4' ||
    substr(md5(random()::text || clock_timestamp()::text), 1, 3) || '-a' ||
    substr(md5(random()::text || clock_timestamp()::text), 1, 3) || '-' ||
    substr(md5(random()::text || clock_timestamp()::text), 1, 12)
  )::uuid
$$;

-- ---------------------------------------------------------------- auth -----
DO $$ BEGIN
  CREATE TYPE public.app_role AS ENUM ('admin','viewer');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS public.app_users (
  id            uuid PRIMARY KEY DEFAULT public.app_uuid(),
  nama          text NOT NULL,
  username      text NOT NULL UNIQUE,
  password_hash text NOT NULL,
  role          text NOT NULL DEFAULT 'viewer',
  is_active     boolean NOT NULL DEFAULT true,
  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.user_roles (
  id         uuid PRIMARY KEY DEFAULT public.app_uuid(),
  user_id    uuid NOT NULL REFERENCES public.app_users(id) ON DELETE CASCADE,
  role       public.app_role NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (user_id, role)
);

CREATE TABLE IF NOT EXISTS public.auth_refresh_tokens (
  token      uuid PRIMARY KEY DEFAULT public.app_uuid(),
  user_id    uuid NOT NULL REFERENCES public.app_users(id) ON DELETE CASCADE,
  expires_at timestamptz NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_refresh_user ON public.auth_refresh_tokens (user_id);

DO $$
DECLARE
  cols_giro text := 'periode text, kode_kanwil text, kanwil text, kode_kanca text, kanca text, kode_uker text, uker text, curr text, currdesc text, cifno text, account_number text, product_code text, status text, short_name text, open_date text, balance text, avail_balance text, limit_amount text, cr_int text, dr_int text, commitment text, avrg_balance text, pn_pengelola_single_pn text, pn_customer_service text, pn_rm_dana text, pn_rm_pinjaman text, pn_rm_merchant text, pn_relationship_officer text, pn_sales_person text, pn_pab text, pn_rm_referral text';
  cols_delta text := 'norek text, nama_nasabah text, tgl1 text, tgl2 text, rm_pengelola text';
  cols_depo text := 'periode text, kode_uker text, cur_code text, cur_desc text, type text, acctno text, fdr_srl_no text, principal_amount text, short_name text, withdrawable_int text, issue_dt text, mat_dt text, int_rate text, int_tenor_disp text, renew text, remark text, pn_customer_service text, pn_rm_dana text, pn_rm_pinjaman text, pn_rm_merchant text, pn_relationship_officer text, pn_sales_person text, pn_pab text, pn_rm_referral text, jumlah_pn text, cbal_base text';
  cols_di319 text := 'periode text, uker_code text, curr_code text, curr_desc text, account_number text, ciff_no text, short_name text, open_dt text, balance text, in_balance text, accrued_int text, average_balance text, prod_code text, pn_pengelola_singlepn text, pn_customer_service text, pn_rm_dana_mantri text, pn_rm_pinjaman text, pn_rm_merchant text, pn_relationship_officer_rm_kredit_menengah text, pn_sales_person text, pn_pab text, pn_rm_referral text, jumlah_pn_pemasar text, balance_dalam_idr text';
  grp record;
BEGIN
  FOR grp IN
    SELECT unnest(ARRAY['data_di321_data1','data_di321_data2','data_di321_data3','data_mtd_giro','data_mtd_tab','data_ytd_giro','data_ytd_tab']) AS name, cols_giro AS cols
    UNION ALL
    SELECT unnest(ARRAY['data_mtd_giro_kenaikan','data_mtd_giro_penurunan','data_mtd_tab_kenaikan','data_mtd_tab_penurunan','data_ytd_giro_kenaikan','data_ytd_giro_penurunan','data_ytd_tab_kenaikan','data_ytd_tab_penurunan']), cols_delta
    UNION ALL
    SELECT unnest(ARRAY['data_depo','data_depo_data1','data_depo_data2','data_depo_data3']), cols_depo
    UNION ALL
    SELECT unnest(ARRAY['data_di319_data1','data_di319_data2','data_di319_data3']), cols_di319
  LOOP
    EXECUTE format('CREATE TABLE IF NOT EXISTS public.%I (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, %s)', grp.name, grp.cols);
  END LOOP;
END $$;

CREATE TABLE IF NOT EXISTS public.activity_logs (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username text NOT NULL,
  action text NOT NULL,
  description text DEFAULT ''::text NOT NULL,
  ip_address text DEFAULT ''::text NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS public.data_edc (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tahun text, periode text, posisi text, kode_kanwil text, nama_kanwil text, kode_kanca text, nama_kanca text, kode_uker text, nama_uker text, tid text, mid text, nama_merchant text, jenis text, kanwil_pemrakarsa text, kanwil_nama_pemrakarsa text, uker_pemrakarsa text, uker_nama_pemrakarsa text, kanwil_implementor text, kanwil_nama_implementor text, uker_implementor text, uker_nama_implementor text, pn_user_pemrakarsa text, nama_user_pemrakarsa text, last_available text, status_available text, last_utility text, status_utility text, last_transactional text, status_transactional text, alamat_merchant text, kelurahan text, kecamatan text, kabupaten text, provinsi text, aktif_or_staging text, jml_transaksi text, sales_volume text, akumulasi_transaksi text, akumulasi_sales_volume text, kartu_jml_transaksi_on_us text, kartu_jml_transaksi_off_us text, jml_transaksi_qris text, kartu_sales_volume_on_us text, kartu_sales_volume_off_us text, sales_volume_qris text, ket_mcc text, kode_mcc text, norek text, cifno text, saldo_posisi text, ratas_saldo text, saldo_posisi_by_cif text, ratas_saldo_by_cif text, tgl_approval text, nilai text, source text, sales_volume_mid text, flagging text, flagging_bri_merchant text, tiering_sales_volume text, status_edc text
);

CREATE TABLE IF NOT EXISTS public.data_qris (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  periode text, posisi text, region text, rgdesc text, mainbr text, mbdesc text, branch text, x text, brdesc text, merchant_pan text, storeid text, nama_merchant text, kriteria text, jenis_usaha text, kode_mcc text, mcc text, alamat text, kode_pos text, kota text, provinsi text, no_rek text, cif text, pn text, pn_pemrakasa text, jabatan text, tgl_balikan_pten text, status text, merchant_type text, akumulasi_sv_onus text, akumulasi_sv_offus text, akumulasi_sv_linkaja text, akumulasi_sv_total text, posisi_sv_total text, akumulasi_trx_onus text, akumulasi_trx_offus text, akumulasi_trx_linkaja text, akumulasi_trx_total text, posisi_trx_total text, saldo_posisi text, ratas_saldo text, flagging_bri_merchant text, status_qris text
);

CREATE TABLE IF NOT EXISTS public.data_pic_jalan (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  no_urut text, unit_kerja text, nama_rmft text, nama_jalan text, nama_toko text, usaha text, rek_bri text, edc_bri text, qris_bri text, rek_lain text, edc_lain text, qris_lain text, telpon text, owner text, keterangan text, follow_up_terakhir text
);

CREATE TABLE IF NOT EXISTS public.data_pivot_multi (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  seq text, no_rek text, nama text, valuta text, jenis_rekening text, tanggal_transaksi text, jam_transaksi text, kode_transaksi text, desk_transaksi text, saldo_awal_mutasi text, mutasi_debet text, mutasi_kredit text, saldo_akhir_mutasi text, truser text, glsign text, auxtrc text, uker_tran text, uker_desc_tran text
);

CREATE TABLE IF NOT EXISTS public.data_produktivitas_rmft (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rm text, dpk text, tgl1 text, tgl2 text, tgl3 text
);

CREATE TABLE IF NOT EXISTS public.links (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nama text NOT NULL,
  url text NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS public.settings (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key text NOT NULL UNIQUE,
  value text NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_data_qris_periode ON public.data_qris (periode);
CREATE INDEX IF NOT EXISTS idx_data_edc_periode ON public.data_edc (periode);
CREATE INDEX IF NOT EXISTS idx_di319_1_periode ON public.data_di319_data1 (periode);
CREATE INDEX IF NOT EXISTS idx_di319_2_periode ON public.data_di319_data2 (periode);
CREATE INDEX IF NOT EXISTS idx_di319_3_periode ON public.data_di319_data3 (periode);

CREATE OR REPLACE FUNCTION public.has_role(_user_id uuid, _role public.app_role)
RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT EXISTS (SELECT 1 FROM public.user_roles WHERE user_id = _user_id AND role = _role)
$$;

CREATE TABLE IF NOT EXISTS public.calendar_events (
  id BIGSERIAL PRIMARY KEY,
  tanggal DATE NOT NULL,
  judul TEXT NOT NULL,
  warna TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
INSERT INTO public.calendar_events (tanggal, judul, warna)
SELECT * FROM (VALUES
  ('2026-08-03'::date, 'HBD CI YULI', 'amber'),
  ('2026-08-04'::date, 'YAMAHA BAHANA', 'green'),
  ('2026-08-04'::date, 'SHANKARA', 'pink'),
  ('2026-08-06'::date, 'PELINDO', 'blue')
) v WHERE NOT EXISTS (SELECT 1 FROM public.calendar_events);

CREATE OR REPLACE FUNCTION public.run_compare(_kind text)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  src_table text; base_table text; bal_col text; rm_col text;
  up_table text; down_table text; sql text; n_up int; n_down int;
BEGIN
  -- Otorisasi admin dilakukan di lapisan API Node.js (JWT app_role).

  IF _kind = 'mtd_giro' THEN
    src_table := 'data_di321_data2'; base_table := 'data_di321_data3';
    bal_col := 'balance'; rm_col := 'pn_rm_dana';
    up_table := 'data_mtd_giro_kenaikan'; down_table := 'data_mtd_giro_penurunan';
  ELSIF _kind = 'ytd_giro' THEN
    src_table := 'data_di321_data1'; base_table := 'data_di321_data3';
    bal_col := 'balance'; rm_col := 'pn_rm_dana';
    up_table := 'data_ytd_giro_kenaikan'; down_table := 'data_ytd_giro_penurunan';
  ELSIF _kind = 'mtd_tab' THEN
    src_table := 'data_di319_data2'; base_table := 'data_di319_data3';
    bal_col := 'balance'; rm_col := 'pn_rm_dana_mantri';
    up_table := 'data_mtd_tab_kenaikan'; down_table := 'data_mtd_tab_penurunan';
  ELSIF _kind = 'ytd_tab' THEN
    src_table := 'data_di319_data1'; base_table := 'data_di319_data3';
    bal_col := 'balance'; rm_col := 'pn_rm_dana_mantri';
    up_table := 'data_ytd_tab_kenaikan'; down_table := 'data_ytd_tab_penurunan';
  ELSE
    RAISE EXCEPTION 'unknown compare kind %', _kind;
  END IF;

  EXECUTE format('DELETE FROM public.%I', up_table);
  EXECUTE format('DELETE FROM public.%I', down_table);

  sql := format(
    'WITH j AS (SELECT b.account_number AS norek, COALESCE(b.short_name, s.short_name) AS nama,'
    ' COALESCE(NULLIF(regexp_replace(s.%1$I, ''[^0-9.-]'', '''', ''g''), '''')::numeric, 0) AS v1,'
    ' COALESCE(NULLIF(regexp_replace(b.%1$I, ''[^0-9.-]'', '''', ''g''), '''')::numeric, 0) AS v2,'
    ' COALESCE(b.%2$I, s.%2$I) AS rm'
    ' FROM public.%3$I b JOIN public.%4$I s ON s.account_number = b.account_number)'
    ' INSERT INTO public.%5$I (norek, nama_nasabah, tgl1, tgl2, rm_pengelola)'
    ' SELECT norek, nama, v1::text, v2::text, rm FROM j WHERE v2 > v1',
    bal_col, rm_col, base_table, src_table, up_table);
  EXECUTE sql;
  GET DIAGNOSTICS n_up = ROW_COUNT;

  sql := format(
    'WITH j AS (SELECT b.account_number AS norek, COALESCE(b.short_name, s.short_name) AS nama,'
    ' COALESCE(NULLIF(regexp_replace(s.%1$I, ''[^0-9.-]'', '''', ''g''), '''')::numeric, 0) AS v1,'
    ' COALESCE(NULLIF(regexp_replace(b.%1$I, ''[^0-9.-]'', '''', ''g''), '''')::numeric, 0) AS v2,'
    ' COALESCE(b.%2$I, s.%2$I) AS rm'
    ' FROM public.%3$I b JOIN public.%4$I s ON s.account_number = b.account_number)'
    ' INSERT INTO public.%5$I (norek, nama_nasabah, tgl1, tgl2, rm_pengelola)'
    ' SELECT norek, nama, v1::text, v2::text, rm FROM j WHERE v2 < v1',
    bal_col, rm_col, base_table, src_table, down_table);
  EXECUTE sql;
  GET DIAGNOSTICS n_down = ROW_COUNT;

  RETURN jsonb_build_object('ok', true, 'kenaikan', n_up, 'penurunan', n_down);
END;
$$;

-- --------------------------------------------------------------- seed ------
INSERT INTO public.app_users (nama, username, password_hash, role, is_active)
VALUES ('Administrator', 'admin', '$2b$10$qvqKO6Wt2b55dRlF/WN/R.i.jjrp5IEo.w3zMTLu33QYM2JXvXybW', 'admin', true)
ON CONFLICT (username) DO NOTHING;

INSERT INTO public.user_roles (user_id, role)
SELECT id, 'admin'::public.app_role FROM public.app_users WHERE username = 'admin'
ON CONFLICT DO NOTHING;

-- Bersihkan refresh token kedaluwarsa (jalankan berkala via cron cPanel bila perlu)
DELETE FROM public.auth_refresh_tokens WHERE expires_at < now();
