/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompareDataRouteImport } from './routes/compare-data'
import { Route as LinksRouteImport } from './routes/links'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as UsersRouteImport } from './routes/users'
import { Route as DataSlugRouteImport } from './routes/data.$slug'
import { Route as ApiPublicAuthV1SplatRouteImport } from './routes/api/public/auth/v1/$'
import { Route as ApiPublicRestV1SplatRouteImport } from './routes/api/public/rest/v1/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareDataRoute = CompareDataRouteImport.update({
  id: '/compare-data',
  path: '/compare-data',
  getParentRoute: () => rootRouteImport,
} as any)
const LinksRoute = LinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const DataSlugRoute = DataSlugRouteImport.update({
  id: '/data/$slug',
  path: '/data/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAuthV1SplatRoute = ApiPublicAuthV1SplatRouteImport.update({
  id: '/api/public/auth/v1/$',
  path: '/api/public/auth/v1/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRestV1SplatRoute = ApiPublicRestV1SplatRouteImport.update({
  id: '/api/public/rest/v1/$',
  path: '/api/public/rest/v1/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compare-data': typeof CompareDataRoute
  '/links': typeof LinksRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
  '/data/$slug': typeof DataSlugRoute
  '/api/public/auth/v1/$': typeof ApiPublicAuthV1SplatRoute
  '/api/public/rest/v1/$': typeof ApiPublicRestV1SplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compare-data': typeof CompareDataRoute
  '/links': typeof LinksRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
  '/data/$slug': typeof DataSlugRoute
  '/api/public/auth/v1/$': typeof ApiPublicAuthV1SplatRoute
  '/api/public/rest/v1/$': typeof ApiPublicRestV1SplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compare-data': typeof CompareDataRoute
  '/links': typeof LinksRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
  '/data/$slug': typeof DataSlugRoute
  '/api/public/auth/v1/$': typeof ApiPublicAuthV1SplatRoute
  '/api/public/rest/v1/$': typeof ApiPublicRestV1SplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compare-data'
    | '/links'
    | '/login'
    | '/logs'
    | '/settings'
    | '/users'
    | '/data/$slug'
    | '/api/public/auth/v1/$'
    | '/api/public/rest/v1/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compare-data'
    | '/links'
    | '/login'
    | '/logs'
    | '/settings'
    | '/users'
    | '/data/$slug'
    | '/api/public/auth/v1/$'
    | '/api/public/rest/v1/$'
  id:
    | '__root__'
    | '/'
    | '/compare-data'
    | '/links'
    | '/login'
    | '/logs'
    | '/settings'
    | '/users'
    | '/data/$slug'
    | '/api/public/auth/v1/$'
    | '/api/public/rest/v1/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompareDataRoute: typeof CompareDataRoute
  LinksRoute: typeof LinksRoute
  LoginRoute: typeof LoginRoute
  LogsRoute: typeof LogsRoute
  SettingsRoute: typeof SettingsRoute
  UsersRoute: typeof UsersRoute
  DataSlugRoute: typeof DataSlugRoute
  ApiPublicAuthV1SplatRoute: typeof ApiPublicAuthV1SplatRoute
  ApiPublicRestV1SplatRoute: typeof ApiPublicRestV1SplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare-data': {
      id: '/compare-data'
      path: '/compare-data'
      fullPath: '/compare-data'
      preLoaderRoute: typeof CompareDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/links': {
      id: '/links'
      path: '/links'
      fullPath: '/links'
      preLoaderRoute: typeof LinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data/$slug': {
      id: '/data/$slug'
      path: '/data/$slug'
      fullPath: '/data/$slug'
      preLoaderRoute: typeof DataSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auth/v1/$': {
      id: '/api/public/auth/v1/$'
      path: '/api/public/auth/v1/$'
      fullPath: '/api/public/auth/v1/$'
      preLoaderRoute: typeof ApiPublicAuthV1SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/rest/v1/$': {
      id: '/api/public/rest/v1/$'
      path: '/api/public/rest/v1/$'
      fullPath: '/api/public/rest/v1/$'
      preLoaderRoute: typeof ApiPublicRestV1SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompareDataRoute: CompareDataRoute,
  LinksRoute: LinksRoute,
  LoginRoute: LoginRoute,
  LogsRoute: LogsRoute,
  SettingsRoute: SettingsRoute,
  UsersRoute: UsersRoute,
  DataSlugRoute: DataSlugRoute,
  ApiPublicAuthV1SplatRoute: ApiPublicAuthV1SplatRoute,
  ApiPublicRestV1SplatRoute: ApiPublicRestV1SplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
