// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { getSupabaseRuntimeConfig } from '@/lib/runtime-config';

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}


function createSupabaseClient() {
  // Self-hosted mode: the API lives on this same app under /api/public, so the
  // browser can derive the base URL from its own origin. That keeps the build
  // portable — no domain baked into the bundle.
  const runtime = getSupabaseRuntimeConfig();
  const envUrl =
    runtime?.url ||
    import.meta.env['VITE_SUPABASE_URL'] ||
    process.env['SB_URL'] ||
    process.env['SUPABASE_URL'];
  const browserOrigin =
    typeof window !== 'undefined' ? `${window.location.origin}/api/public` : undefined;
  const SUPABASE_URL =
    envUrl && envUrl !== 'self'
      ? envUrl
      : (browserOrigin ??
        // Self-hosted SSR: no window and no absolute URL configured. Data is
        // always fetched from the browser, so a loopback placeholder is enough
        // and keeps server rendering from crashing with a 500.
        `http://127.0.0.1:${process.env['PORT'] || 3000}/api/public`);
  const SUPABASE_PUBLISHABLE_KEY =
    runtime?.publishableKey ||
    import.meta.env['VITE_SUPABASE_PUBLISHABLE_KEY'] ||
    process.env['SB_PUBLISHABLE_KEY'] ||
    process.env['SUPABASE_PUBLISHABLE_KEY'] ||
    'self-hosted';



  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

